[package]
name = "mandelbrot_explorer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "0.4.0"
sdl2 = { version = "0.34", features = [ "ttf" ] }
rayon = "1.6.1"
palette = "0.1.1"